version: "3.9"
services:
  # timescabledb:
  #   image: timescale/timescaledb:latest-pg14
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ./timescale/data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_PASSWORD=pass1234 # superuser :postgres


#  timescabledb-ha:
#    image: timescale/timescaledb-ha:pg14-latest
#    ports:
#      - "5432:5432"
#    volumes:
#      - ./timescale/data:/home/postgres/pgdata/data
#    environment:
#      - POSTGRES_PASSWORD=pass1234 # superuser :postgres
#    deploy:
#      replicas: 0
#
#  redis:
#    image: redis
#    ports:
#      - "6379:6379"
#    volumes:
#      - ./redis/data:/data
#
#  zookeeper:
#    image: confluentinc/cp-zookeeper:latest
#    environment:
#      ZOOKEEPER_CLIENT_PORT: 2181
#      ZOOKEEPER_TICK_TIME: 2000
#    ports:
#      - 22181:2181
#    deploy:
#      replicas: 0
#
#  kafka:
#    image: confluentinc/cp-kafka:latest
#    depends_on:
#      - zookeeper
#    ports:
#      - 29092:29092
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#    deploy:
#      replicas: 0
#
#  grafana:
#    image: grafana/grafana-oss
#    ports:
#      - 3001:3000
#    restart: always
#    volumes:
#      - ./grafana:/var/lib/grafana
#    deploy:
#      replicas: 0

  mysql:
    image: mysql:8
    command: './init.sh'
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass1234
    volumes:
      - ./mysql:/var/lib/mysql
      - ./mysql-init.sh:/init.sh
    ports:
      - "3306:3306"
    deploy:
      replicas: 0

  h2:
    image: oscarfonts/h2:1.4.199
    restart: always
    ports:
      - "1521:1521"
      - "81:81"
    environment:
      H2_OPTIONS: -ifNotExists