spring:
  datasource:
    url: jdbc:h2:mem:tommazon;MODE=MYSQL;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false
  flyway:
    enabled: true  # Enable Flyway database migration
    locations: classpath:db/common/schema
    validate-on-migrate: true
    baseline-on-migrate: true
    fail-on-missing-locations: true
server:
  port: 8432

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - mappings
          - beans